### ISSUE TITLE
Research a pipeline execution environment based on docker

### ISSUE THREAD

**Issue by white-gecko** [AKSW/shapbird#6]

**Comment by luckyos-code** [comment]
Created a Make+Docker workflow for now in 69fa44830f6654083a7326213175e3495be9616d
Looking further to eliminate Make

**Comment by white-gecko** [comment]
You should look into https://n8n.io/ and https://github.com/gbaeke/webhookd

**Comment by white-gecko** [comment]
See also:
    DOCKER_HOST=/tmp/docker.sock docker-compose -H $DOCKER_HOST /data/docker-compose.yml up

https://github.com/jwilder/nginx-proxy
